### ISSUE TITLE
printsupport module unavailable for printing

### ISSUE THREAD

**Issue by markummitchell** [ubuntu/snapcraft-desktop-helpers#110]
Hello,
I am trying to understand how printing should work. File libQt5PrintSupport.so is not copied into the staging directory even when "QT+=printsupport" is specified, so there is a runtime error about that file missing. Your project's qt/launcher-specific file sets QT_PRINTER_MODULE to qtubuntu-print which is advertised as sending a pdf file to an application that is normally specified on the same line as qtubuntu-print. If I remove "QT+=printsupport" then compilation crashes since header file QPrinterDialog is no longer available. Thanks in advance for your help

**Comment by markummitchell** [comment]
Got it. My working version, which is not optimized, is:

```
name: engauge-digitizer
version: '10.6'
summary: Interactively convert a bitmap graph or map into numbers.
description: Software tool for extracting numbers from images of graphs and maps.
grade: stable
confinement: strict

parts:
  engauge-digitizer:
    plugin: qmake
    options: [CONFIG+=log4cpp_null, CONFIG+=pdf, QT+=printsupport, QT+=sql]
    qt-version: qt5
    build-packages: [qttools5-dev, libqt5gui5, libqt5sql5-sqlite, libfftw3-double3, libpoppler-dev, libpoppler-qt5-dev]
    stage-packages: [qttools5-dev, libqt5gui5, libqt5sql5-sqlite, libfftw3-double3, libpoppler-dev, libpoppler-qt5-dev]
    project-files: [engauge.pro]
    after: [help]
  help:
    plugin: dump
    stage: [engauge, documentation/engauge.qch, documentation/engauge.qhc]
    after: [desktop-qt5]
apps:
  engauge-digitizer:
    command: desktop-launch $SNAP/engauge
    plugs: [home, cups-control]
```
