### ISSUE TITLE
errno.h no such file or directory

### ISSUE THREAD

**Issue by gocarlos** [ubuntu/snapcraft-desktop-helpers#214]
when trying to build a snap:

```
...
Building gnome-3-34-extension 
make -j2
gcc -Wall -O2 -o bindtextdomain.so -fPIC -shared ./../src/bindtextdomain.c -ldl
./../src/bindtextdomain.c:5:10: fatal error: errno.h: No such file or directory
 #include <errno.h>
          ^~~~~~~~~
compilation terminated.
Makefile:20: recipe for target 'desktop-launch' failed
make: *** [desktop-launch] Error 1
Failed to run 'make -j2' for 'gnome-3-34-extension': Exited with code 2.
Verify that the part is using the correct parameters and try again.
```

the snapcraft:

```yaml
...
apps:
  myapp:
    command: myapp
    plugs:
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
    extensions: [gnome-3-34]
    desktop: myapp.desktop

parts:
...

```

I'm using core18 but using gcc9 in my for my parts...
eventually related to https://github.com/ubuntu/snapcraft-desktop-helpers/pull/119

if I leave the `desktop: myapp.desktop` out, then the snap build right, though no desktop launcher available then
