### ISSUE TITLE
Fails on package installation

### ISSUE THREAD

**Issue by phw** [ubuntu/snapcraft-desktop-helpers#55]
I am trying to build a GTK3 app with the desktop-gtk3 part. This is how my parts definition looks like:

```
parts:
  peek:
    plugin: cmake
    source: .
    after:
      - desktop-gtk3
    build-packages:
      - libgtk-3-dev
      - gettext
      - valac
```

When I run `snapcraft` the "pull desktop-gtk3" stage fails with:

```
tar: ./usr/lib/x86_64-linux-gnu/libxml2.so.2: Cannot create symlink to ‘libxml2.so.2.9.3’: Read-only file system
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2
/media/sf_devel/peek/parts/desktop-gtk3/ubuntu/download/libxml2_2.9.3+dfsg1-1ubuntu0.1_amd64.deb
```

Full output at https://gist.github.com/phw/4810ed87b36458dba697322d2c746fcd

Trying this on an up-to-date Ubuntu 16.04 installation with snapcraft 2.27. What am I doing wrong?
