### ISSUE TITLE
desktop-launch integration with a script

### ISSUE THREAD

**Issue by egara** [ubuntu/snapcraft-desktop-helpers#8]
Hi

I'm snapping an application called [wallpaperdownloader](https://github.com/ubuntu/snappy-playpen/tree/master/wallpaperdownloader) which downloads wallpapers fromt the Internet. So far so good. But now I'm developing version 2.2 with a new feature: A button to set the wallpaper selected for the Desktop. Natively, the java application is working fine for Unity and GNOME3, but my problem is that I cannot make it work inside a snap package. I've been digging around and I wrote an e-mail to snapcraft mailing list and a user pointed to my to this direction. I need to use gsettings command line tool from my snapped application and I don't know how to do it.

I have tried to use snapcraft-desktop-helpers part but I suspect I don't use it in a proper way. This is my snapcraft.yaml file (please, be aware that I need to execute a script called wallpaperdownloader.sh as command in order to export some environment variables)

```
name: wallpaperdownloader
version: "2.2"
summary: Download and manage your favorite wallpapers from the Internet
description: WallpaperDownloader is a simple GUI Java based application for downloading and managing wallpapers from the Internet
confinement: strict

apps:
  wallpaperdownloader:
    command: desktop-launch wallpaperdownloader.sh
    plugs: [x11, network-bind, home, gsettings]

parts:
  # Pulls the code from the original source (master branch)
  wallpaperdownloader:
    plugin: maven
    source: .
    after: [desktop/gtk3]

  # It will copy wallpaperdownloader script into /bin/
  # This script contains all the commands needed (sets env variables, launches the jar file...) to
  # execute the application
  exec:
    plugin: copy
    files:
      wallpaperdownloader.sh: bin/wallpaperdownloader.sh

```

When I install the snap package generated, first, the desktop launcher  doesn't have the icon defined in /setup/gui. Second, the launcher doesn't do anything apparently.

This is the script wallpaperdownloader.sh

```
#!/bin/sh
# Only for packaging!
# Script for snap packaging wallpaperdownloader application. It is not related to the code itself
# Not good, needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
# Font Config
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
export HOME=$SNAP_USER_DATA
java -jar -Duser.home=$SNAP_USER_DATA $SNAP/jar/wallpaperdownloader.jar
```

What is the problem? Using desktop-launch can I read and write values with gsettings? Thank you very much for your time :)

Best,

Eloy
